newIssueWelcomeComment: >
  Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and open and issue on https://developercommunity.visualstudio.com for the particular package.
